### ISSUE TITLE
Implement called-n-times-with?

### ISSUE THREAD

**Issue by alexanderjamesking** [alexanderjamesking/spy#10]
Implement `called-n-times-with?`

something like

```clj
(defn called-n-times-with?
  [pred f n]
  (= n (count (filter pred (spy/calls f)))))
```

example usage:

```clj
(called-n-times-with? 
  (fn [call]
    (= [{:id 123 :url "/job-id/123"}] call))
   mock-request
   2)
```

Needs more test cases, and relevant macro / fn in assert namespaces for clj and cljs

**Comment by alexanderjamesking** [comment]
`called-once-with?` should perhaps also be renamed `called-exactly-once-with?` and `called-once-with?` changed to return true when one call matches without the restriction of just one call to the spy

**Comment by alexanderjamesking** [comment]
Duplicate of https://github.com/alexanderjamesking/spy/pull/12

**Comment by christophe-riolo** [comment]
> `called-once-with?` should perhaps also be renamed `called-exactly-once-with?` and `called-once-with?` changed to return true when one call matches without the restriction of just one call to the spy

Hello !
I am digging this suggestion out, as this behaviour surprised me. I guess this is an unwanted breaking change now, but it would be nice to make that less restricted version.
Also at the same time, I think that the `spy.assert` namespace is missing some equivalents of `spy.core` I'd be happy to participate in the actual coding, but I guess specification of the change should be made by you at least 😃
