### ISSUE TITLE
Idea: integrating spy's rich assertions with clojure.test's assert-expr multimethod

### ISSUE THREAD

**Issue by robhanlon22** [alexanderjamesking/spy#14]
Here's an example of extending the capabilities of `clojure.test/is` by defining a handler for the `assert-expr` multimethod in nubank/matcher-combinators: https://github.com/nubank/matcher-combinators/blob/master/src/clj/matcher_combinators/clj_test.clj#L38

Defining `assert-expr`s for `called?`, `called-with?`, etc. would be super handy—it would make it so consumers don't have to know about the extra `assert` namespace in order to get rich assertion failure information.

**Comment by robhanlon22** [comment]
Oh and btw I love the library! Definitely wraps up some patterns I would have rolled on my own.

**Comment by alexanderjamesking** [comment]
Thanks, I think it's a nice idea and it could remove the need for the separate `assert` namespace (It could remain to avoid breaking changes for library users but I guess it wouldn't be needed in the longer term).

I'd happily review + accept a PR on this if you'd like to have a go at implementing it @robhanlon22

**Comment by robhanlon22** [comment]
Yup, I’ll do it! Just wanted to gauge interest first.

**Comment by alexanderjamesking** [comment]
clj implementation in #15, cljs implementation in #17 

Thanks to @robhanlon22 🍻
